2022-11-05 14:45:56,247 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:50]
2022-11-05 14:46:37,176 ERROR: Exception on /edit_profile [POST] [in /home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/app/routes.py", line 102, in edit_profile
    if form.validate_on_submit():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate()
                                   ^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/wtforms/form.py", line 329, in validate
    return super().validate(extra)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/wtforms/form.py", line 146, in validate
    if not field.validate(self, extra):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/wtforms/fields/core.py", line 242, in validate
    stop_validation = self._run_validation_chain(form, chain)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/.venv/lib/python3.11/site-packages/wtforms/fields/core.py", line 262, in _run_validation_chain
    validator(form, self)
  File "/home/vlasov/Yandex.Disk/myprojects/microblog/app/forms.py", line 63, in validate_username
    if username.data != self.original_username:
                        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EditProfileForm' object has no attribute 'original_username'
2022-11-05 14:47:48,886 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:50]
2022-11-05 14:53:20,930 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:50]
2022-11-07 14:44:00,046 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:50]
2022-11-07 14:44:30,099 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:50]
2022-11-07 14:44:44,647 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:50]
2022-11-07 15:50:23,846 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:50]
2022-11-07 15:56:58,020 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:50]
2022-11-07 15:57:07,096 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:50]
2022-11-07 16:09:21,060 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:50]
2022-11-07 16:09:32,595 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:50]
2022-11-07 16:09:43,721 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:50]
2022-11-07 16:18:56,440 INFO: Microblog startup [in /home/vlasov/Yandex.Disk/myprojects/microblog/app/__init__.py:50]
